# Generated by Django 5.1 on 2024-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villages',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Desa'),
        ),
    ]
