# Generated by Django 5.1 on 2024-09-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_villages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villages',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.district'),
        ),
    ]
