# Generated by Django 5.1 on 2024-09-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_villages_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=250, verbose_name='Alamat Kirim')),
                ('post_code', models.CharField(max_length=10, verbose_name='Kode Pos')),
                ('cust_note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Catatan Pembeli')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='customers.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='customers.district')),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='customers.province')),
                ('village', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='customers.villages')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
