# Generated by Django 5.1 on 2024-09-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_address_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
    ]
