# Generated by Django 5.1 on 2024-09-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_customer_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.villages'),
        ),
    ]
