# Generated by Django 5.1 on 2024-10-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_address_city_alter_address_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cust_note',
        ),
    ]
