# Generated by Django 5.1 on 2024-10-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_cityrajaongkir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityRajaOngkir',
        ),
    ]
