# Generated by Django 5.1 on 2024-10-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_delete_cityrajaongkir'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRajaOngkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kabupaten / Kota')),
                ('city_name', models.CharField(blank=True, max_length=250, verbose_name='Nama')),
                ('postal_code', models.CharField(blank=True, max_length=250, verbose_name='Nama')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.provincerajaongkir')),
            ],
        ),
    ]
