# Generated by Django 5.1 on 2024-10-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_cityrajaongkir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.cityrajaongkir'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.provincerajaongkir'),
        ),
    ]
