# Generated by Django 5.1 on 2024-09-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0010_remove_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=1, max_length=500, unique=True, verbose_name='Session ID'),
            preserve_default=False,
        ),
    ]
