# Generated by Django 5.1 on 2024-09-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_id',
            new_name='order',
        ),
    ]
