# Generated by Django 5.1 on 2024-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_guest_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cust_note',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Catatan Customer'),
        ),
    ]
