# Generated by Django 5.1 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MK1', 'Menunggu Konfirmasi'), ('DP2', 'Diproses'), ('SD3', 'Dikirim'), ('ST4', 'Sampai Tujuan')], default='MK1', max_length=3),
            preserve_default=False,
        ),
    ]
