# Generated by Django 5.1 on 2024-10-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_address_user'),
        ('orders', '0007_order_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_final',
        ),
        migrations.AddField(
            model_name='order',
            name='nomor_resi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor Resi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.address', verbose_name='Alamat Penerima'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MK1', 'Menunggu Konfirmasi'), ('DP2', 'Diproses'), ('SD3', 'Dikirim'), ('ST4', 'Sampai Tujuan')], max_length=3, verbose_name='Status Pesanan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna Terkait'),
        ),
    ]
