# Generated by Django 5.1 on 2024-10-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_total_order_total_final_order_nomor_resi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nomor_resi',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomor Resi'),
        ),
    ]
