# Generated by Django 5.1 on 2024-10-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_nomor_resi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agen_pengiriman',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agen Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_pengiriman',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Berat'),
        ),
    ]
