# Generated by Django 5.1 on 2024-09-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Product Slug'),
        ),
    ]
