# Generated by Django 5.1 on 2024-09-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
