# Generated by Django 5.1 on 2024-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_tokopedia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Tokopedia'),
        ),
    ]
