# Generated by Django 5.1 on 2024-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_link_tokopedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, null=True, verbose_name='Berat Produk (g)'),
        ),
    ]
