# Generated by Django 5.1 on 2024-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Barang Terjual'),
        ),
    ]
